# Generated by Django 4.2.6 on 2023-10-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_reviews', models.BooleanField(default=True)),
                ('share_library', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='personal_library',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='library.library'),
        ),
        migrations.AddField(
            model_name='reader',
            name='profile_picture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reader',
            name='preferences',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.readerpreferences'),
        ),
    ]
