# Generated by Django 4.2.5 on 2023-10-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_readerpreferences_reader_bio_reader_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='profile_picture',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
