# Generated by Django 4.2.5 on 2023-10-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_reader_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='profile_picture',
            field=models.IntegerField(default=0),
        ),
    ]
