# Generated by Django 4.2.5 on 2023-10-29 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
    ]
